# Generated by Django 4.2 on 2023-04-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailName', models.CharField(max_length=100, verbose_name='Detail Name')),
                ('Count', models.IntegerField(verbose_name='Count of details')),
                ('DeliveryCountry', models.CharField(max_length=100, verbose_name='Delivery Country')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailName', models.CharField(max_length=100, verbose_name='Detail Name')),
                ('Count', models.IntegerField(verbose_name='Count of details')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShippingName', models.CharField(max_length=50, verbose_name='Name of order')),
                ('ShippingDate', models.DateField(verbose_name='Date when order came')),
                ('DeliveryCountry', models.CharField(max_length=100, verbose_name='Delivery Country')),
                ('Details', models.ManyToManyField(to='main.shippingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderName', models.CharField(max_length=50, verbose_name='Name of order')),
                ('OrderDate', models.DateField(verbose_name='Date when order came')),
                ('Details', models.ManyToManyField(to='main.details')),
            ],
        ),
    ]
