# Generated by Django 4.1.2 on 2023-06-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_address_orders_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
