# Generated by Django 4.1.2 on 2023-06-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_pickupaddress_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Address', to='main.pickupaddress'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Airports', to='main.airports'),
        ),
    ]
