# Generated by Django 4.1.2 on 2023-06-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_orders_address_alter_orders_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Airport', to='main.airports'),
        ),
    ]
